Repository KonataDev/Konata.Core, pull requests merged in 2020-10, with the labels that each got.

#21 Merge some features
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Network/PacketMan.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Tlv/T146.cs
  Konata.Core/Msf/Packets/Tlv/T191.cs
  Konata.Core/Msf/Packets/Tlv/T508.cs
  Konata.Core/Msf/Packets/Tlv/Tlv.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Debug/DevToolsProtocol/Browser.cs
  Konata.Debug/DevToolsProtocol/Session.cs
  Konata.Debug/Konata.Debug.csproj
  Konata.Debug/Program.cs
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ

#22 Passed the slider captcha
  Konata.Core/Bot.cs
  Konata.Core/DeviceInfo.cs
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Network/PacketMan.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/SsoMan.cs
  Konata.Debug/DevToolsProtocol/Browser.cs
  Konata.Debug/DevToolsProtocol/Session.cs
  Konata.Debug/Program.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#23 update README.md
  README.md
Labels: documentation (ง •_•)ง

#25 some features
  Konata.Console/App.config
  Konata.Console/DevToolsProtocol/Browser.cs
  Konata.Console/DevToolsProtocol/Session.cs
  Konata.Console/Konata.Console.csproj
  Konata.Console/Program.cs
  Konata.Core/AppInfo.cs
  Konata.Core/Bot.cs
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestCheckSms.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestRefreshSms.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTgtgt.cs
  Konata.Core/Msf/Packets/Tlv/T17b.cs
  Konata.Core/Msf/Packets/Tlv/Tlv.cs
  Konata.Core/Msf/Packets/Tlv/TlvUnpacker.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/WtLoginSession.cs
  Konata.Device/DeviceInfo.cs
  Konata.Device/Konata.Device.csproj
  Konata.Device/Properties/AssemblyInfo.cs
  Konata.Device/Tree/DeviceTree.cs
  Konata.Device/Tree/Samsung/klte.cs
  Konata.Test/App.config
  Konata.Test/Konata.Test.csproj
  Konata.Test/Program.cs
  Konata.Test/Properties/AssemblyInfo.cs
  Konata.sln
  README.md
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ

#26 passed the sms verification
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestCheckSms.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestRefreshSms.cs
  Konata.Core/Msf/Packets/Tlv/T174.cs
  Konata.Core/Msf/Packets/Tlv/T178.cs
  Konata.Core/Msf/Packets/Tlv/T179.cs
  Konata.Core/Msf/Packets/Tlv/Tlv.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/WtLoginSession.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#28 update readme
  README.md
Labels: documentation (ง •_•)ง

#30 fix issue
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/SsoMan.cs
Labels: bug (っ °Д °;)っ

#31 upgrade Library.IO
  Konata.Core/Msf/Packet.cs
  Konata.Library.IO/ByteBuffer.cs
  Konata.Library.IO/ByteConverter.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#33 fix _wPos counting bug
  Konata.Library.IO/ByteBuffer.cs
Labels: bug (っ °Д °;)っ

#34 unify parameter 'prefixLength's into 'prefixFlag'
  Konata.Core/Msf/Packet.cs
  Konata.Core/Msf/Packets/FromServiceMessage.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTransport.cs
  Konata.Core/Msf/Packets/Tlv/T106.cs
  Konata.Core/Msf/Packets/Tlv/T11a.cs
  Konata.Core/Msf/Packets/Tlv/T11d.cs
  Konata.Core/Msf/Packets/Tlv/T124.cs
  Konata.Core/Msf/Packets/Tlv/T128.cs
  Konata.Core/Msf/Packets/Tlv/T141.cs
  Konata.Core/Msf/Packets/Tlv/T142.cs
  Konata.Core/Msf/Packets/Tlv/T146.cs
  Konata.Core/Msf/Packets/Tlv/T147.cs
  Konata.Core/Msf/Packets/Tlv/T148.cs
  Konata.Core/Msf/Packets/Tlv/T177.cs
  Konata.Core/Msf/Packets/Tlv/T178.cs
  Konata.Core/Msf/Packets/Tlv/T17c.cs
  Konata.Core/Msf/Packets/Tlv/T17d.cs
  Konata.Core/Msf/Packets/Tlv/T192.cs
  Konata.Core/Msf/Packets/Tlv/T2.cs
  Konata.Core/Msf/Packets/Tlv/T202.cs
  Konata.Core/Msf/Packets/Tlv/T508.cs
  Konata.Core/Msf/Packets/Tlv/T511.cs
  Konata.Library.IO/ByteBuffer.cs
  Konata.Library.JceStruct/JceOutputStream.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#36 jcestruct
  Konata.Core/Msf/Packet.cs
  Konata.Library.IO/ByteBuffer.cs
  Konata.Library.JceStruct/JceTreeRoot.cs
  Konata.Library.JceStruct/JceUtils.cs
  Konata.Library.JceStruct/Konata.Library.JceStruct.csproj
  Konata.Test/Konata.Test.csproj
  Konata.Test/Test.cs
  Konata.Test/Tests/TestJceStruct.cs
  Konata.Test/Tests/TestProtobufSerialize.cs
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ

#37 some fixes
  Konata.Core/Msf/Packets/Svc/SvcReq.cs
  Konata.Core/Msf/Packets/Svc/SvcReqEmpty.cs
  Konata.Core/Msf/Packets/Svc/SvcReqRegister.cs
  Konata.Core/Msf/Packets/Wup/UniPacket.cs
  Konata.Library.IO/ByteBuffer.cs
  Konata.Library.JceStruct/JceInputStream.cs
  Konata.Library.JceStruct/JceOutputStream.cs
  Konata.Library.JceStruct/JceTreeRoot.cs
  Konata.Library.JceStruct/JceUtils.cs
  Konata.Library.JceStruct/Konata.Library.JceStruct.csproj
  Konata.Test/Konata.Test.csproj
  Konata.Test/Tests/TestJceStruct.cs
  Konata.Test/Tests/TestJceWriter.cs
  Konata.Test/Tests/TestSvcReqEmpty.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#39 fix jce parser
  .github/workflows/test.yml
  Konata.Library.JceStruct/JceTreeRoot.cs
  Konata.Test/Program.cs
  Konata.Test/Tests/TestJceStruct.cs
  Konata.Test/Tests/TestSvcReqRegister.cs
Labels: bug (っ °Д °;)っ
