Repository KonataDev/Konata.Core, pull requests merged in 2020-09, with the labels that each got.

#1 Added barrier methods to Packet; fixed TlvBase
  konata.core/Msf/Packet.cs
  konata.core/Msf/Packets/Tlv/TlvBase.cs
Labels: enhancement

#3 commit files
  konata.core/Msf/Network/PacketMan.cs
  konata.core/Msf/Packet.cs
  konata.core/Msf/Packets/FromServiceMessage.cs
  konata.core/Msf/Packets/Sso/SsoMessage.cs
  konata.core/Msf/SsoMan.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#4 replace reflection with dictionary
  konata.core/Msf/ServiceRoutine.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#5 conbine Service and ServiceRoutine
  konata.core/Msf/Service.cs
  konata.core/Msf/ServiceRoutine.cs
  konata.core/Msf/Services/JsApiSvr/WebView/WhiteList.cs
  konata.core/Msf/Services/Wtlogin/Login.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#6 update BufferIO and Packet, finish Take*** methods
  konata.core/Msf/Core.cs
  konata.core/Msf/Packet.cs
  konata.core/Msf/ServiceRoutine.cs
  konata.core/Msf/Services/GrayUinPro/Check.cs
  konata.core/Msf/SsoMan.cs
  konata.core/Utils/BufferIO.cs
  konata.core/konata.core.csproj
Labels: enhancement (｡･∀･)ﾉﾞ

#7 add LICENSE
  .gitignore
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Service.cs
  Konata.Core/Msf/Services/GrayUinPro/Check.cs
  Konata.Core/Msf/Services/JsApiSvr/WebView/WhiteList.cs
  Konata.Core/Msf/Services/Wtlogin/ExchangeEmp.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/Services/Wtlogin/PushChangeToken.cs
  Konata.Core/prebuild.scanservice.bat
  Konata.Core/prebuild.scanservice.sh
  LICENSE
Labels: enhancement (｡･∀･)ﾉﾞ

#10 merge changes
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Packet.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestCheckImage.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestCheckSms.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTgtgt.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/SsoMan.cs
  README.md
Labels: enhancement (｡･∀･)ﾉﾞ

#11 create packet bodies
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Tlv/T1.cs
  Konata.Core/Msf/Packets/Tlv/TlvBase.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#12 merge changes
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Crypto/KeyRing.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTgtgt.cs
  Konata.Core/Msf/Packets/Tlv/T1.cs
  Konata.Core/Msf/Packets/Tlv/T100.cs
  Konata.Core/Msf/Packets/Tlv/T104.cs
  Konata.Core/Msf/Packets/Tlv/T106.cs
  Konata.Core/Msf/Packets/Tlv/T107.cs
  Konata.Core/Msf/Packets/Tlv/T108.cs
  Konata.Core/Msf/Packets/Tlv/T109.cs
  Konata.Core/Msf/Packets/Tlv/T116.cs
  Konata.Core/Msf/Packets/Tlv/T124.cs
  Konata.Core/Msf/Packets/Tlv/T128.cs
  Konata.Core/Msf/Packets/Tlv/T141.cs
  Konata.Core/Msf/Packets/Tlv/T142.cs
  Konata.Core/Msf/Packets/Tlv/T144.cs
  Konata.Core/Msf/Packets/Tlv/T145.cs
  Konata.Core/Msf/Packets/Tlv/T147.cs
  Konata.Core/Msf/Packets/Tlv/T148.cs
  Konata.Core/Msf/Packets/Tlv/T153.cs
  Konata.Core/Msf/Packets/Tlv/T154.cs
  Konata.Core/Msf/Packets/Tlv/T166.cs
  Konata.Core/Msf/Packets/Tlv/T16e.cs
  Konata.Core/Msf/Packets/Tlv/T177.cs
  Konata.Core/Msf/Packets/Tlv/T18.cs
  Konata.Core/Msf/Packets/Tlv/T187.cs
  Konata.Core/Msf/Packets/Tlv/T188.cs
  Konata.Core/Msf/Packets/Tlv/T191.cs
  Konata.Core/Msf/Packets/Tlv/T192.cs
  Konata.Core/Msf/Packets/Tlv/T193.cs
  Konata.Core/Msf/Packets/Tlv/T194.cs
  Konata.Core/Msf/Packets/Tlv/T2.cs
  Konata.Core/Msf/Packets/Tlv/T202.cs
  Konata.Core/Msf/Packets/Tlv/T318.cs
  Konata.Core/Msf/Packets/Tlv/T511.cs
  Konata.Core/Msf/Packets/Tlv/T516.cs
  Konata.Core/Msf/Packets/Tlv/T521.cs
  Konata.Core/Msf/Packets/Tlv/T525.cs
  Konata.Core/Msf/Packets/Tlv/T52d.cs
  Konata.Core/Msf/Packets/Tlv/T536.cs
  Konata.Core/Msf/Packets/Tlv/T544.cs
  Konata.Core/Msf/Packets/Tlv/T545.cs
  Konata.Core/Msf/Packets/Tlv/T8.cs
  Konata.Core/Msf/Packets/Tlv/TlvBase.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  README.md
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ

#13 finish tlv unpack methods
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Packet.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTgtgt.cs
  Konata.Core/Msf/Packets/Tlv/T1.cs
  Konata.Core/Msf/Packets/Tlv/T100.cs
  Konata.Core/Msf/Packets/Tlv/T104.cs
  Konata.Core/Msf/Packets/Tlv/T106.cs
  Konata.Core/Msf/Packets/Tlv/T107.cs
  Konata.Core/Msf/Packets/Tlv/T108.cs
  Konata.Core/Msf/Packets/Tlv/T109.cs
  Konata.Core/Msf/Packets/Tlv/T116.cs
  Konata.Core/Msf/Packets/Tlv/T124.cs
  Konata.Core/Msf/Packets/Tlv/T128.cs
  Konata.Core/Msf/Packets/Tlv/T141.cs
  Konata.Core/Msf/Packets/Tlv/T142.cs
  Konata.Core/Msf/Packets/Tlv/T144.cs
  Konata.Core/Msf/Packets/Tlv/T145.cs
  Konata.Core/Msf/Packets/Tlv/T147.cs
  Konata.Core/Msf/Packets/Tlv/T148.cs
  Konata.Core/Msf/Packets/Tlv/T153.cs
  Konata.Core/Msf/Packets/Tlv/T154.cs
  Konata.Core/Msf/Packets/Tlv/T166.cs
  Konata.Core/Msf/Packets/Tlv/T16e.cs
  Konata.Core/Msf/Packets/Tlv/T177.cs
  Konata.Core/Msf/Packets/Tlv/T18.cs
  Konata.Core/Msf/Packets/Tlv/T187.cs
  Konata.Core/Msf/Packets/Tlv/T188.cs
  Konata.Core/Msf/Packets/Tlv/T191.cs
  Konata.Core/Msf/Packets/Tlv/T192.cs
  Konata.Core/Msf/Packets/Tlv/T193.cs
  Konata.Core/Msf/Packets/Tlv/T194.cs
  Konata.Core/Msf/Packets/Tlv/T2.cs
  Konata.Core/Msf/Packets/Tlv/T202.cs
  Konata.Core/Msf/Packets/Tlv/T318.cs
  Konata.Core/Msf/Packets/Tlv/T511.cs
  Konata.Core/Msf/Packets/Tlv/T516.cs
  Konata.Core/Msf/Packets/Tlv/T521.cs
  Konata.Core/Msf/Packets/Tlv/T525.cs
  Konata.Core/Msf/Packets/Tlv/T52d.cs
  Konata.Core/Msf/Packets/Tlv/T536.cs
  Konata.Core/Msf/Packets/Tlv/T544.cs
  Konata.Core/Msf/Packets/Tlv/T545.cs
  Konata.Core/Msf/Packets/Tlv/T8.cs
  Konata.Core/Msf/Packets/Tlv/Tlv.cs
  Konata.Core/Msf/Packets/Tlv/TlvBase.cs
  Konata.Core/Msf/Packets/Tlv/TlvPacker.cs
  Konata.Core/Msf/Packets/Tlv/TlvUnpacker.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ

#14 merge new features
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Packet.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTgtgt.cs
  Konata.Core/Msf/Packets/Tlv/T1.cs
  Konata.Core/Msf/Packets/Tlv/T100.cs
  Konata.Core/Msf/Packets/Tlv/T104.cs
  Konata.Core/Msf/Packets/Tlv/T106.cs
  Konata.Core/Msf/Packets/Tlv/T107.cs
  Konata.Core/Msf/Packets/Tlv/T108.cs
  Konata.Core/Msf/Packets/Tlv/T109.cs
  Konata.Core/Msf/Packets/Tlv/T116.cs
  Konata.Core/Msf/Packets/Tlv/T124.cs
  Konata.Core/Msf/Packets/Tlv/T128.cs
  Konata.Core/Msf/Packets/Tlv/T141.cs
  Konata.Core/Msf/Packets/Tlv/T142.cs
  Konata.Core/Msf/Packets/Tlv/T144.cs
  Konata.Core/Msf/Packets/Tlv/T145.cs
  Konata.Core/Msf/Packets/Tlv/T147.cs
  Konata.Core/Msf/Packets/Tlv/T148.cs
  Konata.Core/Msf/Packets/Tlv/T153.cs
  Konata.Core/Msf/Packets/Tlv/T154.cs
  Konata.Core/Msf/Packets/Tlv/T166.cs
  Konata.Core/Msf/Packets/Tlv/T16e.cs
  Konata.Core/Msf/Packets/Tlv/T177.cs
  Konata.Core/Msf/Packets/Tlv/T18.cs
  Konata.Core/Msf/Packets/Tlv/T187.cs
  Konata.Core/Msf/Packets/Tlv/T188.cs
  Konata.Core/Msf/Packets/Tlv/T191.cs
  Konata.Core/Msf/Packets/Tlv/T192.cs
  Konata.Core/Msf/Packets/Tlv/T193.cs
  Konata.Core/Msf/Packets/Tlv/T194.cs
  Konata.Core/Msf/Packets/Tlv/T2.cs
  Konata.Core/Msf/Packets/Tlv/T202.cs
  Konata.Core/Msf/Packets/Tlv/T318.cs
  Konata.Core/Msf/Packets/Tlv/T511.cs
  Konata.Core/Msf/Packets/Tlv/T516.cs
  Konata.Core/Msf/Packets/Tlv/T521.cs
  Konata.Core/Msf/Packets/Tlv/T525.cs
  Konata.Core/Msf/Packets/Tlv/T52d.cs
  Konata.Core/Msf/Packets/Tlv/T536.cs
  Konata.Core/Msf/Packets/Tlv/T544.cs
  Konata.Core/Msf/Packets/Tlv/T545.cs
  Konata.Core/Msf/Packets/Tlv/T8.cs
  Konata.Core/Msf/Packets/Tlv/Tlv.cs
  Konata.Core/Msf/Packets/Tlv/TlvBase.cs
  Konata.Core/Msf/Packets/Tlv/TlvPacker.cs
  Konata.Core/Msf/Packets/Tlv/TlvUnpacker.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#16 begin writing events
  Konata.Core/Bot.cs
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Event.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Debug/Program.cs
Labels: enhancement (｡･∀･)ﾉﾞ

#17 system to user interoperations
  Konata.Core/Bot.cs
  Konata.Core/Konata.Core.csproj
  Konata.Core/Msf/Core.cs
  Konata.Core/Msf/Event.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestCheckImage.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestCheckSms.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequestTgtgt.cs
  Konata.Core/Msf/Service.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Debug/Program.cs
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ

#19 submit slider captcha ticket
  Konata.Core/Bot.cs
  Konata.Core/Msf/Event.cs
  Konata.Core/Msf/Packets/Oicq/OicqRequest.cs
  Konata.Core/Msf/Packets/Tlv/T193.cs
  Konata.Core/Msf/Services/Wtlogin/Login.cs
  Konata.Core/Msf/SsoMan.cs
  Konata.Debug/Program.cs
Labels: bug (っ °Д °;)っ, enhancement (｡･∀･)ﾉﾞ
